version: '3'

vars:
  CONFIG_DIR: '{{.ROOT_DIR}}/config'
  CUSTOM_COMPONENTS: '{{.ROOT_DIR}}/custom_components'

tasks:
  ha:run:
    desc: Run Home Assistant in foreground (Docker)
    cmds:
      - docker compose up homeassistant

  ha:dev:
    desc: Alias for ha:run
    cmds:
      - task: ha:run

  ha:up:
    desc: Start Home Assistant in daemon mode
    cmds:
      - docker compose up -d homeassistant

  ha:down:
    desc: Stop Home Assistant container
    cmds:
      - docker compose stop homeassistant

  ha:restart:
    desc: Restart Home Assistant container
    cmds:
      - docker compose restart homeassistant

  ha:logs:
    desc: Tail Home Assistant logs
    cmds:
      - docker compose logs -f homeassistant

  ha:shell:
    desc: Access Home Assistant container shell
    cmds:
      - docker compose exec homeassistant bash

  clean:
    desc: Clean config directory
    cmds:
      - rm -r {{.CONFIG_DIR}}

  install:
    desc: Install dependencies
    cmds:
      - uv sync

  # Infrastructure/Grocy container management
  grocy:up:
    desc: Start grocy container in daemon mode
    cmds:
      - docker compose up -d grocy

  grocy:down:
    desc: Stop and remove grocy containers
    cmds:
      - docker compose down grocy

  grocy:restart:
    desc: Restart grocy containers
    cmds:
      - docker compose restart grocy

  grocy:logs:
    desc: Show grocy container logs
    cmds:
      - docker compose logs -f grocy

  grocy:shell:
    desc: Access grocy container shell
    cmds:
      - docker compose exec grocy bash
